### ISSUE TITLE
329 docker compose error nodeid na

### ISSUE THREAD

**Issue by tooptoop4** [Lewuathe/docker-presto-cluster#8]
PRESTO_VERSION=329 docker-compose up

worker0        | 
worker0        | 1) Error: Invalid configuration property node.id: is malformed (for class io.airlift.node.NodeConfig.nodeId)
worker0        | 
worker0        | 1 error
worker0        | com.google.inject.CreationException: Unable to create injector, see the following errors:
worker0        | 
worker0        | 1) Error: Invalid configuration property node.id: is malformed (for class io.airlift.node.NodeConfig.nodeId)
worker0        | 
worker0        | 1 error
worker0        | 	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
worker0        | 	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
worker0        | 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
worker0        | 	at com.google.inject.Guice.createInjector(Guice.java:87)
worker0        | 	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:240)
worker0        | 	at io.prestosql.server.PrestoServer.run(PrestoServer.java:120)
worker0        | 	at io.prestosql.server.PrestoServer.main(PrestoServer.java:70)
worker0        | 
worker0        | 
worker1        | 2020-03-08T15:33:00.561Z	ERROR	main	io.prestosql.server.PrestoServer	Unable to create injector, see the following errors:
worker1        | 
worker1        | 1) Error: Invalid configuration property node.id: is malformed (for class io.airlift.node.NodeConfig.nodeId)
worker1        | 
worker1        | 1 error
worker1        | com.google.inject.CreationException: Unable to create injector, see the following errors:
worker1        | 
worker1        | 1) Error: Invalid configuration property node.id: is malformed (for class io.airlift.node.NodeConfig.nodeId)
worker1        | 
worker1        | 1 error
worker1        | 	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
worker1        | 	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
worker1        | 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
worker1        | 	at com.google.inject.Guice.createInjector(Guice.java:87)
worker1        | 	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:240)
worker1        | 	at io.prestosql.server.PrestoServer.run(PrestoServer.java:120)
worker1        | 	at io.prestosql.server.PrestoServer.main(PrestoServer.java:70)
worker1        | 
worker1        | 
worker0 exited with code 1
worker1 exited with code 1
coordinator    | 2020-03-08T15:33:01.622Z	ERROR	main	io.prestosql.server.PrestoServer	Unable to create injector, see the following errors:
coordinator    | 
coordinator    | 1) Error: Invalid configuration property node.id: is malformed (for class io.airlift.node.NodeConfig.nodeId)
coordinator    | 
coordinator    | 1 error
coordinator    | com.google.inject.CreationException: Unable to create injector, see the following errors:
coordinator    | 
coordinator    | 1) Error: Invalid configuration property node.id: is malformed (for class io.airlift.node.NodeConfig.nodeId)
coordinator    | 
coordinator    | 1 error
coordinator    | 	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
coordinator    | 	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
coordinator    | 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
coordinator    | 	at com.google.inject.Guice.createInjector(Guice.java:87)
coordinator    | 	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:240)
coordinator    | 	at io.prestosql.server.PrestoServer.run(PrestoServer.java:120)
coordinator    | 	at io.prestosql.server.PrestoServer.main(PrestoServer.java:70)
coordinator    | 
coordinator    | 
coordinator exited with code 1

log has
worker0        | 2020-03-08T15:11:28.481Z	INFO	main	Bootstrap	node.id                                                                 ----                                                                       -- n/a --

**Comment by tooptoop4** [comment]
@Lewuathe what command should I run as workaround?

**Comment by Lewuathe** [comment]
@tooptoop4 Sorry for the trouble. From 330, the image gets the coordinator address as the first argument. The latest `docker-compose.yml` supports [this format](https://github.com/Lewuathe/docker-presto-cluster#usage).

To run the old version before 329, the `docker-compose.yml` should look like this. Please note that the command section given to each container. 

```yaml
version: '3'

services:
  coordinator:
    image: "lewuathe/presto-coordinator:${PRESTO_VERSION}"
    ports:
      - "8080:8080"
    container_name: "coordinator"
    command: coordinator
  worker0:
    image: "lewuathe/presto-worker:${PRESTO_VERSION}"
    container_name: "worker0"
    ports:
      - "8081:8081"
    command: worker0
  worker1:
    image: "lewuathe/presto-worker:${PRESTO_VERSION}"
    container_name: "worker1"
    ports:
      - "8082:8081"
    command: worker1

```
