### ISSUE TITLE
330 docker compose java11 error

### ISSUE THREAD

**Issue by tooptoop4** [Lewuathe/docker-presto-cluster#9]
PRESTO_VERSION=330 docker-compose up

Recreating coordinator ... done
Recreating worker1     ... done
Recreating worker0     ... done
Attaching to worker1, coordinator, worker0
worker0        | Rendered etc/node.properties
worker0        | Rendered etc/config.properties
worker1        | Rendered etc/node.properties
worker1        | Rendered etc/config.properties
coordinator    | Rendered etc/node.properties
coordinator    | Rendered etc/config.properties
coordinator    | ERROR: Future versions of Presto will require Java 11 after March 2020.
coordinator    | 
coordinator    | You may temporarily continue running on Java 8 by adding the following
coordinator    | JVM config option:
coordinator    | 
coordinator    |     -Dpresto-temporarily-allow-java8=true
coordinator    | 
worker0        | ERROR: Future versions of Presto will require Java 11 after March 2020.
worker0        | 
worker0        | You may temporarily continue running on Java 8 by adding the following
worker0        | JVM config option:
worker0        | 
worker0        |     -Dpresto-temporarily-allow-java8=true
worker0        | 
worker1        | ERROR: Future versions of Presto will require Java 11 after March 2020.
worker1        | 
worker1        | You may temporarily continue running on Java 8 by adding the following
worker1        | JVM config option:
worker1        | 
worker1        |     -Dpresto-temporarily-allow-java8=true
worker1        | 
coordinator exited with code 100
worker0 exited with code 100
worker1 exited with code 100

**Comment by Lewuathe** [comment]
@tooptoop4 We should have used JDK 11 in the docker image since 330. Thanks for reporting. Will fix that.
